### ISSUE TITLE
Wie kann ich dieses Addon in Redaxo Base_Demo integrieren?

### ISSUE THREAD

**Issue by ghost** [FriendsOfREDAXO/blogger#1]
Hallo Andy, kann ich dich auf Deutsch etwas fragen? Ich habe Redaxo 5.x-Base-Demo installiert und habe den ersten Beispiel-Artikel kurz verfasst. Kategorien und Tags habe ich auch angelegt und ich würde gerne das Blog in der Navigation in der Demo verlinken. 

Wie muss ich dabei vorgehen? Redaxo ist noch sehr neu für mich und komplizierter als andere CMS wie Wordpress und Co. 

Danke im Vorfeld.

**Comment by AndyBitz** [comment]
Hi Alex,
blogger bietet im Moment eine API an mit der man auf die Daten der Einträge zugreifen kann.
Diese API kann unter anderem in Templates und Modulen benutzt werden.

Um beispielsweise einen Blog auf einer Unterseite namens _Blog_ zu integrieren muss man folgendes tun:
1. Ein neues Modul erstellen. Den Namen kann man frei wählen, input und output können erstmal leer bleiben.
2. Neue Kategorie bzw. neuen Artikel namens _Blog_ erstellen.
3. In diesem Artikel muss dann das neue Modul eingefügt werden.

Als nächstes muss die ganze Logik ins Modul.
Grundsätzlich entscheidet das Modul was schlussendlich im Frontend angezeigt wird.

Als Beispiel:
Standardmäßig soll das Modul eine Vorschau für die letzen 5 Einträge anzeigen.
Sobald man einen Eintrag auswählt kommt man zur Seite des Eintrags.

Der output des Moduls würde dann ungefähr so aussehen:
```php
<?php 
  
  // Hiermit kann man auf die Daten zugreifen
  $myBlogger = new Blogger();

  // ID des abgefragten Eintrags (ist in der url bsp. www.website.com/blog/?post=2)
  // 0 falls keiner abgefraft wird
  $postId = rex_get('post', 'integer', 0);

  if ($postId !== 0) {
    // Zeige den Blogeintrag den der Nutzer sehen will

    // In $entry sind jetzt die Daten für den eintrag mit der id $postId gespeichert
    $entry = $myBlogger->getEntry($postId);

    $content = $entry['content'][1]; // 1 ist die Standardsprache

    // zeige Titel, Text, Vorschau Bild und Galerie Bilder
    echo $content['title'];
    echo $content['text'];
    echo $content['preview'];
    echo $content['gallery'];

    // zeige Kategorie
    echo $entry['categoryName'];

    $tags = $entry['tags'];

    // zeige Tags
    foreach ($tags as $tag) {
      echo $tag['tag'];
    }

  } else {
    // Zeige die letzen 5 Blogeinträge

    // in $lastEntries ist ein Array mit den letzen 5 einträgen gespeichert
    $lastEntries = $myBlogger->getLastEntries("0, 5"); // "0, 5" gibt das Suchlimit an

    foreach ($lastEntries as $entry) {

      $content = $entry['content'][1]; // 1 ist die Standardsprache

      // zeige Titel und Vorschau Bild
      echo $content['title'];
      echo $content['preview'];

      // zeige Kategorie
      echo $entry['categoryName'];

      $tags = $entry['tags'];

      // zeige alle Tags
      foreach ($tags as $tag) {
        echo $tag['tag'];
      }

      // /blog funktioniert nur, wenn man sich das Modul auf dieser Seite befindet.
      // ansonsten sollte man es austauschen bzw. dynamisch anhand der URL ermitteln
      $url = '/blog/?post='.$entry['id'];
      echo '<a href="'.$url.'">zum Post</a>';
    }

  }
?>
```
Ein Beispiel für ein komplettes Modul findest du [hier](https://github.com/AndyBitz/rex_blogger/blob/master/examples/full-output-module.php).

Ich will noch eine einfachere integration ermöglichen bzw. ein bearbeitbares Modul gleich mitliefern um es mehr einsteigerfreundlich zu machen.

Ich hoffe das hilft dir erstmal weiter, falls du noch Fragen hast oder hilfe brauchst, sag einfach Bescheid.

**Comment by ghost** [comment]
Danke bis hierher und ich brauche weitere Hilfestellung. Wenn ich beim Blog dann bin, kann ich in den Blocks im Editiermodus das vorher erstellte Module nicht finden. Es ist nicht verfügbar. Dem Modul habe ich im Output den Code, den du mir zeigtest, hinzugefügt. Woran liegt es dann noch?


Ich kann im Editiermodus beim erstellten Artikel nur Blöcke auswählen, die in der Redaxo Base Demo installiert sind. Aber Module sind nicht da. Auch komme ich an die Modul-ID heran, weiss aber nicht, wie ich es dann im Editiermodus des Artikels einbinden kann. Kannst du mir vielleicht weiter helfen. Danke im Vorfeld.

**Comment by AndyBitz** [comment]
Ahh, in der Demo sind die einzelnen Module in den Templates festgelegt. Um das neue Modul benutzen zu können musst du einfach unter Templates im entsprechenden Template unter dem Reiter _Kategorieberechtigungen_ das Modul hinzufügen.
