### ISSUE TITLE
blogger in englisch

### ISSUE THREAD

**Issue by danielellm** [FriendsOfREDAXO/blogger#3]
hallo,
ich haber das blogger addon instaliert
ich verwende derzeit zwei sprachen..
bei tags und kategorien funktioniert es einwandfrei nur bei einträge habe ich nur die deutsche variante aber es werden zwei einträge in die datenbank geschrieben (deutsch mit inhalt - englisch ohne inhalt)
wie wo kann ich das ändern?

lg

**Comment by AndyBitz** [comment]
Hi,

insofern die Sprachen online geschaltet sind, sollten sie als eigene Tabs bei den Einträgen angezeigt werden.
<img width="494" alt="bildschirmfoto 2018-11-06 um 18 50 29" src="https://user-images.githubusercontent.com/16088670/48083228-f1374080-e1f4-11e8-9f71-e472b8205556.png">

Kategorien und Tags ignorieren ob eine Sprache online oder offline ist, es zeigt einfach die Inputfelder für alle an.

**Comment by danielellm** [comment]
Leider sieht das so nicht bei mir aus..🤔
Was kann ich tun?

Am Di., 6. Nov. 2018, 18:52 hat Andy <notifications@github.com> geschrieben:

**Comment by AndyBitz** [comment]
Seltsam 🤔 

Wie sehen deine Sprachen im System aus?
![image](https://user-images.githubusercontent.com/16088670/48086139-64908080-e1fc-11e8-993c-1add594e9d13.png)

Und wie sieht deine Seite für einen neuen Eintrag aus? Vielleicht hilft ein Screenshot davon schon.

**Comment by AWqxKAWERbXo** [comment]
close?
