### ISSUE TITLE
Neues Datenfeld in Tabelle rex_blogger_entries

### ISSUE THREAD

**Issue by mad1988** [FriendsOfREDAXO/blogger#4]
Hallo Andy Bitz,

erstmal ein Lob für dein AddOn :).
Ich würde gerne weitere Datenfelder der Tabele rex_blogger_entries hinzufügen (Sichtbar von: und Sichtbar bis: ) wie geh ich hier am besten vor?

**Comment by AndyBitz** [comment]
Hi Mad,

danke fürs Lob :)

Falls du nichts direkt am Code vom AddOn verändern willst, dann kannst du theoretisch den Table Manager vom `yform` AddOn benutzen. Das ganze wird dann zwar in einer separaten Tabelle und einem eigenen Menüpunkt gemacht, aber das ganze ist die schnellere und einfachere Lösung.
Es müsste im Table Manager nur eine Tabelle mit der ID für den Eintrag angelegt werden und dazu zwei Felder für "Sichtbar von" und "Sichtbar bis". Die Tabelle müsste dann nur vor der eigentlichen ausgaben abgefragt werden und falls der Eintrag im Zeitraum ist, dann wird er angezeigt, ansonsten eben übersprungen und nicht angezeigt.


**Ansonsten, direkt im AddOn:**

Als erstes müssten die zwei Felder in der [install.php](https://github.com/AndyBitz/rex_blogger/blob/master/install.php#L20) angelegt werden. Zum Beispiel 
`availableFrom` und `availableTill` als Datetime. Die Felder sollten am besten auch `Nullable` sein, damit sie nicht gesetzt werde müssen.

Jetzt müssten in `lib/backend.class.php` die Form-Felder hinzugefügt werden.
Zuletzt müssen noch die APIs angepasst werden, also alles in `lib/api.blogger.class.php` und alles in `lib/blogger.class.php` was irgendwelche abfragen macht. (Hier muss natürlich auch beachtet werden, dass alles valide ist, z.B. das `Till` Datum nicht vor `From` liegt).

Als Bonus könnte dann noch eine extra Checkbox in der Config angelegt werden, um die Felder standardmäßig nicht anzuzeigen.

**Comment by mad1988** [comment]
Vielen Dank...

echt eine super Sache von Dir :) ... 
Ich werde morgen die Lösung über das AddOn umzusetzen.

Evtl. könnte deine Antwort auch für andere Nutzer hilfreich sein... wenn du damit einverstanden bist würde ich deine Lösung in der Slack Community von Redaxo posten (https://friendsofredaxo.slack.com)

...weiter so !!!

**Comment by AndyBitz** [comment]
Auch Danke :)
Darfst du auch gerne Posten
